### ISSUE TITLE
main.hex missing?

### ISSUE THREAD

**Issue by anqixu** [ethz-asl/asctec_mav_framework#17]
Hi Markus:

```
I don't see the main.hex in the current repo under asctec_hl_firmware. Should we be using the hex from 8b99dfbfc159f8779a55c17f2efd83ae60752726, or is this a hint for us to compile our own hex?

Best;
```

Anqi Xu

**Comment by m-kzein** [comment]
@anqixu  could you please help me with the building process? The link to the official wiki of asctec is not working anymore, they shut it down. 
thank you!

**Comment by anqixu** [comment]
Sorry, I don't remember nor have the files since it's been so long...
