### ISSUE TITLE
waypoint_server missing link library of Boost

### ISSUE THREAD

**Issue by prclibo** [ethz-asl/asctec_mav_framework#28]
Hi, I failed to compile due to the absence of Boost in waypoint_server and waypoint_client.
So just suggest to add `${Boost_LIBRARIES}` to waypoint_server and waypoint_client in the [`CMakeLists.txt`](https://github.com/ethz-asl/asctec_mav_framework/blob/master/asctec_hl_interface/CMakeLists.txt#L58).

**Comment by markusachtelik** [comment]
fixed in #29
