### ISSUE TITLE
Compilation Conflict With Multi-Sensor Fusion Package

### ISSUE THREAD

**Issue by XinkeAE** [ethz-asl/asctec_mav_framework#33]
Hi,

Great work! Thanks for providing this great framework to the community!

I'm having trouble in installing the asctec_mav_framework. This is the process I ran through:

1. Got the "catkin_simple" package installed;

2. Got the "glog_catkin" package install;

3. Created a folder ethz_asctec_mav_framework(this can be arbitrary)/src;
    Download the zip file and unzip inside the src folder;
    Run "catkin_make" outside of the src;

The compilation system doesn't like this and just gave me the error:
*******************************Error**********************************
"CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by
  "sensor_fusion_comm" with any of the following names:

    sensor_fusion_commConfig.cmake
    sensor_fusion_comm-config.cmake"
*******************************EndError**********************************
From previous issue, I found this is because I didn't install the sensor_fusion package. I tried to run similar process with the "ethzasl_msf" package and found this error:
*******************************Error**********************************
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "asctec_hl_comm"
  with any of the following names:

    asctec_hl_commConfig.cmake
    asctec_hl_comm-config.cmake
*******************************EndError**********************************
Obviously this is because the framework hasn't been installed. 

Could you please give me some suggestions on this issue?

Thanks!
Xinke

**Comment by markusachtelik** [comment]
hi, 

did you have a look at http://wiki.ros.org/asctec_mav_framework at 4)? There should be all repos listed that you need. clone them all into <your_catkin_ws>/src and run ```catkin_make``` or ```catkin build``` (recommended, http://catkin-tools.readthedocs.org/en/latest/index.html) from <your_catkin_ws>

**Comment by XinkeAE** [comment]
Hi Markus and Sammy,

Thanks for your quick reply. I really appreciate it! :)

I think I found the problem now. At first I just downloaded the four package individually and put them into different folders and compile them separately. 

Now I put them into the same catkin_ws/src and compile it. Although I could get it compiled eventually, I got a small issue when I was using catkin_make to compile it:

At first trial of using "catkin_make", I got the error like:

make: *** [all] Error 2
Invoking "make -j4 -l4" failed

But then I used "catkin_make" again, the compilation continues and succeeded.

Do you have any idea of this issue or I have to use the catkin_tool to compile this?

Thank you guys so much!
