### ISSUE TITLE
No data in ekf_state_out

### ISSUE THREAD

**Issue by XinkeAE** [ethz-asl/asctec_mav_framework#34]
HI,

I'm trying to implement your framework on our asctec pelican. 

I got the asctec_mav_framework compiled on my machine and download the sample parameter file from:

http://wiki.ros.org/ethzasl_sensor_fusion/Tutorials/sfly_framework?action=AttachFile&do=view&target=fcu_parameters.zip

I put the file in folder: 
src/asctec_mav_framework/asctec_hl_interface/launch

And use:
roslaunch asctec_hl_interface fcu.launch to fire the interface node.

1.
Weirdly when I open the rqt_reconfigure I saw the parameter is not the same as the fcu_parameters.yaml. For example:
state_estimation is not HighLevel_EKF but STATE_EST_OFF. 
What should I do to change the default setting?

2. 
I tried to use:
rostopic echo /fcu/ekf_state_out to take a look of the predication result from the micro-controller but I got nothing. Could you guys give me some hints on this?

3. 
To set the framework up, I followed the tutorial:
http://wiki.ros.org/ethzasl_sensor_fusion/Tutorials/sfly_framework
It said I can use the pose_sensor in msf to do sensor fusion, but according to the launch file, the msf_pose_sensor only reads the imu raw data instead of the predicted data from the microcontroller. In this case, I just assume I should change the launch file to get the predicted data(do some remapping). Am I correct?

Thank you guys so much!

-Xinke

**Comment by markusachtelik** [comment]
sorry for that one - in the file, you need to add ```fcu/``` before the parameter names. you can have a look at the example file in this package https://github.com/ethz-asl/asctec_mav_framework/blob/master/asctec_hl_interface/launch/fcu_parameters.yaml

@stephanweiss : could you take care of updating the file on the wiki?

**Comment by XinkeAE** [comment]
Hi Markus,

After changing the parameter file, I can get the ekf_state_out data from the HLP.

Thanks!
