### ISSUE TITLE
New Kernel Conflicts with Wifi Adapter

### ISSUE THREAD

**Issue by XinkeAE** [ethz-asl/asctec_mav_framework#35]
Hi all,

We are trying to follow the tutorial:
http://wiki.ros.org/asctec_mav_framework/Tutorials/onboard_computer_setup
to achieve faster serial communication between the asctec microcontroller and the mastermind.

Our system is xubuntu 14.04 and the mastermind has the i7 processor. We also followed the instruction in the tutorial. Until doing "Install the kernel image and the headers" the wifi adapter worked well, but after installing it and restarting the computer the wifi adapter was no longer being recognized by the system.

Do you have any hints on this issue? We've been working on this for quite a long time. 

Thanks!

**Comment by markusachtelik** [comment]
hi, was the wifi adapter maybe not connected during the ```make localmodconfig``` step? I assume the wifi drivers were simply not built in your new kernel image. you can verify, and in case activate, with ```make menuconfig```

**Comment by markusachtelik** [comment]
I just added a note on the wiki: you may get away with just doing the baudrate configuration on 14.04.

**Comment by XinkeAE** [comment]
Hi Markus,

I think I found a way to avoid this problem without installing a new kernel. I tried to use the AP-PEL cable provided with the asctec UAV and there is no problem with the communication.

If possible, could you please also add this into the wiki?

I have another question: currently asctec recommends to use the ACI(asctec communication interface) to do the communication between mastermind and microcontroller. Do you think it is necessary and beneficial to use the ACI to replace the communication package of this framework.

Thanks!

**Comment by markusachtelik** [comment]
Added a comment in the wiki. 

Re ACI: we developed this before ACI was developed. If you don't want to change anything now, like adding new messages, there is now benefit in changing this over to ACI. We're however working on a re-write/cleanup which is based on ACI, but there is no fixed timeline yet.
