### ISSUE TITLE
Asctec_hi_interface problem fcu.launch errror

### ISSUE THREAD

**Issue by iamfarhan007** [ethz-asl/asctec_mav_framework#36]
hi 
i have flashed the main.hex file form asctec_hl_firmware eclipse project to the HLP of pelican.
after rebooting when i launch the fcu.launch i get

asctec@mastermind:~$ roslaunch asctec_hl_interface fcu.launch
... logging to /home/asctec/.ros/log/8c387702-d920-11e4-a0c7-c4d9879214ea/roslaunch-mastermind-3838.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mastermind:59565/

SUMMARY
========

CLEAR PARAMETERS
 * /fcu/

PARAMETERS
 * /fcu/fcu/baudrate
 * /fcu/fcu/frame_id
 * /fcu/fcu/max_velocity_xy
 * /fcu/fcu/max_velocity_z
 * /fcu/fcu/packet_rate_ekf_state
 * /fcu/fcu/packet_rate_gps
 * /fcu/fcu/packet_rate_imu
 * /fcu/fcu/packet_rate_rc
 * /fcu/fcu/packet_rate_ssdk_debug
 * /fcu/fcu/position_control
 * /fcu/fcu/serial_port
 * /fcu/fcu/state_estimation
 * /fcu/ssdk/omega_0_xy
 * /fcu/ssdk/omega_0_z
 * /fcu/ssdk/p16
 * /fcu/ssdk/p17
 * /fcu/ssdk/p18
 * /fcu/ssdk/p20
 * /fcu/ssdk/p21
 * /fcu/ssdk/p22
 * /fcu/ssdk/p23
 * /fcu/ssdk/p24
 * /fcu/ssdk/p35
 * /fcu/ssdk/p36
 * /fcu/ssdk/p37
 * /fcu/ssdk/p38
 * /fcu/ssdk/p39
 * /fcu/ssdk/p40
 * /fcu/ssdk/p41
 * /fcu/ssdk/p42
 * /fcu/ssdk/p43
 * /fcu/ssdk/p45
 * /fcu/ssdk/p46
 * /fcu/ssdk/p48
 * /fcu/ssdk/p49
 * /fcu/ssdk/p9
 * /fcu/ssdk/tf_ref_frame_id
 * /fcu/ssdk/tf_tracked_frame_id
 * /fcu/ssdk/zeta_xy
 * /fcu/ssdk/zeta_z
 * /rosdistro
 * /rosversion

NODES
  /
    fcu (asctec_hl_interface/hl_node)

auto-starting new master
process[master]: started with pid [3852]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8c387702-d920-11e4-a0c7-c4d9879214ea
process[rosout-1]: started with pid [3865]
started core service [/rosout]
process[fcu-2]: started with pid [3878]
[ INFO] [1427969455.311413960]: INFO: opened serial port /dev/ttyS3 with baudrate 460800
[ INFO] [1427969455.311799123]: configured serial port(s), checking connection ... 
waiting for acknowledged packet timed out
rx timeout
waiting for acknowledged packet timed out
waiting for acknowledged packet timed out
rx timeout
waiting for acknowledged packet timed out
waiting for acknowledged packet timed out
[ERROR] [1427969457.815094252]: failed
[ERROR] [1427969457.815250276]: unable to connect
rx timeout
rx timeout
[fcu-2] process has died [pid 3878, exit code 255, cmd /home/asctec/catkin_ws/devel/lib/asctec_hl_interface/hl_node __name:=fcu __log:=/home/asctec/.ros/log/8c387702-d920-11e4-a0c7-c4d9879214ea/fcu-2.log].
log file: /home/asctec/.ros/log/8c387702-d920-11e4-a0c7-c4d9879214ea/fcu-2*.log

any help?

gest farhan

**Comment by sfolgar** [comment]
Hi Farhan,

i have no deep understanding of the process, but i think it could be due to the fact that you are using `/dev/ttyS3` as serial port. In our configuration, the _mastermind_ is connected to the HLP through `/dev/ttyS2`, as described in the [Mastermind Manual](http://wiki.asctec.de/display/AR/Mastermind+Manual).

Also, from the [onboard computer setup tutorial](http://wiki.ros.org/asctec_mav_framework/Tutorials/onboard_computer_setup), as far as i can remember our pelican installation already had a `/etc/grub.d/09_config_serial` file; but the code was disabled. You have to open that file and comment out (or remove) the `exit 0` line.

Hope this helps.
Sergio

**Comment by iamfarhan007** [comment]
Thanks Sergio
 I followed the masrermind buringup tutorial and increased the clock of derial interface chip.
the node works fine now.

regards
farhan

**Comment by giovannisalierno** [comment]
Hi,
I am trying to communicate with a AscTec Hummingbird through asctec_hl_firmware and with XBee wireless/serial interface, which is able in /dev/ttyUSB0. But I am getting the following error:

[ERROR] [1525482049.803542511]: ERROR: could not open serial port /dev/ttyS2 reason: open: Input/output error
[ERROR] [1525482049.803631840]: unable to connect
[fcu-1] process has died [pid 15550, exit code 255, cmd /home/giovanni/experimentos/asctec_ros/asctec5_ws/devel/lib/asctec_hl_interface/hl_node __name:=fcu __log:=/home/giovanni/.ros/log/d3525b36-4ffa-11e8-8c40-00265e82a72d/fcu-1.log].
log file: /home/giovanni/.ros/log/d3525b36-4ffa-11e8-8c40-00265e82a72d/fcu-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Any help?

**Comment by helenol** [comment]
Yes, @giovannisalierno , you need to change the setting from /dev/ttyS2 to /dev/ttyUSB0 in either the launch file or fcu_parameters.yaml:
https://github.com/ethz-asl/asctec_mav_framework/blob/master/asctec_hl_interface/launch/fcu_parameters.yaml#L1
