### ISSUE TITLE
asctrec_hl_interface Tutorial Problem

### ISSUE THREAD

**Issue by iamfarhan007** [ethz-asl/asctec_mav_framework#38]
Hello

on the pelican mastermind I have
roslaunch ptam ptam.launch
roslaunch asctec hl interface fcu.launch 
Iin fcu parameters launch iv set
 state_estimation to "HighLevel_SSDK
position_control = "HighLevel"
 
rosrun asctec hl interface waypoint server
iv remapped from /vslam/pose_world to /fcu/pose in the ptam.launch.

on the borund pc i following the tutorial on remote launching of ptam described here
http://wiki.ros.org/ethzasl_ptam/Tutorials/remote_ptam
in the dynamic_reconfigure gui i have unchecked listen on_tf

rostopic echo /fcu/pose gives the geometry_msgs/PoseWithCovarianceStamped
form the ETHZASL_PTAM
completed allthe sanity checks here http://wiki.ros.org/asctec_hl_interface/Tutorials/hlp%20position%20control

but STIIL The pelican does not readch the desired hight position descried by the 
rosrun ascec_hl_interface waypoint client 

rether it goes completely out of control

perhaps im missing something

thanks
Farhan

**Comment by iamfarhan007** [comment]
Hi 
 In the dynamic reconfigue gui in fcu parametes all the parametes are same as the fcu_parameters.yaml file except for the position control and state_estimation  they are OFF. Although i set  
fcu/state_estimation:  "Highlevel_SSDK"
fcu/position_control:  "HighLevel"
does anyoune know why these parametrs are not sent / accepted by the HLP
Thanks
Farhan

**Comment by iamfarhan007** [comment]
I managed  to setup the position control setup as follows
![selection_002](https://cloud.githubusercontent.com/assets/10851317/7353204/2cbc5892-ed12-11e4-8b0d-a31936e8c846.jpg)

when i see rosrun asctec_hl_interface polt_position_input
/fcu/dedug/data[22]  should be x-axis value but when i move pelican in y-axis it changes (according to ROS coordinate frames x-forward, y-left, z-up) 
/fcu/dedug/data[23]  should be y-axis value but when i move pelican in x-axis it changes 

where as the asctec coordinate frames are
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363036323735372f313634323631372f38313666366137632d353839302d313165332d383062322d6439666431636661663335362e706e67](https://cloud.githubusercontent.com/assets/10851317/7353316/e530f41e-ed12-11e4-8ee2-26087d5ab3c8.png)

do ineed to do any transformations or remappings to correct the HLP position inputs?
because when i give waypoints by the waypoint client like 0 0 0.1 x x
for altitude control the pelican just goes out of control.

Hoping for a reply soon
Thanks
Farhan

**Comment by stephanweiss** [comment]
Did you try to use the controller with Highlevel_EKF instead of Highlevel_SSDK? Not sure what state the code of Highlevel_SSDK is at the moment. Highlevel_EKF should work if you follow the tutorials of asctec_mav_framework, ethzasl_ptam, and ethzasl_sensor_fusion.

Hope that helps.
