### ISSUE TITLE
Jenkins fails

### ISSUE THREAD

**Issue by fmina** [ethz-asl/asctec_mav_framework#71]
Jenkins build fails with `arm-elf-gcc: not found`. Isn't ARM-GCC installed on jenkins nodes?

**Comment by helenol** [comment]
😢  @fmina why do you do this to me.
The answer is probably not, but we can add it to the setup script here:
https://github.com/ethz-asl/mav_tools/blob/master/mav_install/prepare-jenkins-slave.sh

**Comment by fmina** [comment]
Fixed
