### ISSUE TITLE
asctec_mav_framework does't communicate in HL0 

### ISSUE THREAD

**Issue by carmonaArtBrasil** [ethz-asl/asctec_mav_framework#9]
Hi Markus Achtelik,

We've got an asctec Pelican and we are trying to use the ROS package asctec_mav_framework in ubuntu 12.04. 

We've made the connection in HL0 using the same cable which we should use if we were trying to connect in LL0. We've updated the LL firmware and now it is in version 2.15. Also we flashed the Hl using the atomboard->AP/PEL connection cable and flash magic. Also, the atomboard UART ttyUSB0 is already in the dialout and We certified that it is enabled to read and write. Also, when we compiled the asctec_mav_framework, we had to install eigen library and navfn. Also, we had to modify the namespace from ethzasl_sensor_fusion stack from sensor_fusion_comm to ssf_core and linked with the right classes. All the programs compiled without and error. Now when I try to launch the fcu.launch wich is inside asctec_hl_interface package, it still gets waiting for for acknowledged packet timed out, rx timeout.. until ros shutdown the node. We've already tried to change the baudrate between 9600 until 115200 with no effect in the response of the autopilot. Both autopilot and atomboard are connect to the asctec battery. 

We just had 2 differnt console output, the first one:
waiting for for acknowledged packet timed out
rx timeout
waiting for for acknowledged packet timed out
waiting for for acknowledged packet timed out
waiting for for acknowledged packet timed out

The second one:

INFO: opened serial port /dev/ttyUSB0 with baudrate 115200
configured serial port(s), checking connection ...
checksum error for packet 1,resyncing
checksum error for packet 1,resyncing
checksum error for packet 1,resyncing
checksum error for packet 1,resyncing
checksum error for packet 1,resyncing
checksum error for packet 1,resyncing

**Comment by iamfarhan007** [comment]
Hi , Im trying to fulsh the Pelican HLP wiht the asctec_hl_firmware but i cannot get the Projest to compile here is the error im getting 

**** Build of configuration Default for project original_hl_sdk_2.0 ****

make all 

-------- begin (mode: ROM_RUN) --------
arm-elf-gcc (GCC) 4.1.1
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Linking: main.elf
arm-elf-gcc -mthumb -mcpu=arm7tdmi-s -mthumb-interwork -I. -gdwarf-2 -DROM_RUN -D__WinARM__  -O2 -Wall -Wcast-align -Wimplicit  -Wpointer-arith -Wswitch -Wredundant-decls -Wreturn-type -Wshadow -Wunused -Wa,-adhlns=Common_WinARM/src/Startup.lst  -ICommon_WinARM/inc -Wcast-qual -MD -MP -MF .dep/main.elf.d Common_WinARM/src/Startup.o Common_WinARM/src/swi_handler.o  LL_HL_comm.o mymath.o gpsmath.o sdk.o buzzer.o main.o hardware.o LPC2k_ee.o system.o uart.o syscalls.o i2c.o Common_WinARM/src/irq.o adc.o ssp.o pelican_ptu.o      --output main.elf -nostartfiles -Wl,-Map=main.map,--cref -lc -lc -lgcc -ldeclination -lublox  -lm  -L./  -TCommon_WinARM/LPC2146-ROM.ld
/usr/local/arm7/bin/../lib/gcc/arm-elf/4.1.1/../../../../arm-elf/bin/ld: error: .//libdeclination.a(declination.o) uses software FP, whereas main.elf uses hardware FP
/usr/local/arm7/bin/../lib/gcc/arm-elf/4.1.1/../../../../arm-elf/bin/ld: failed to merge target specific data of file .//libdeclination.a(declination.o)
/usr/local/arm7/bin/../lib/gcc/arm-elf/4.1.1/../../../../arm-elf/bin/ld: error: .//libublox.a(ublox.o) uses software FP, whereas main.elf uses hardware FP
/usr/local/arm7/bin/../lib/gcc/arm-elf/4.1.1/../../../../arm-elf/bin/ld: failed to merge target specific data of file .//libublox.a(ublox.o)
collect2: ld returned 1 exit status
make: *** [main.elf] Error 1

**** Build Finished ****



Thanks 
Farhan

**Comment by markusachtelik** [comment]
Hi, are you on the latest version? This error should have been fixed some time ago already. If the latest version does not help, please open a new issue, since this one seems unrelated. Please also add some "," and "." to improve readability ;)

**Comment by giovannisalierno** [comment]
Hi,

I am using the interface XBee, and could not communicate with asctec_mav_framework, any help?

[ INFO] [1525483506.482499313]: INFO: opened serial port /dev/ttyUSB0 with baudrate 57600
[ INFO] [1525483506.483033116]: configured serial port(s), checking connection ... 
waiting for acknowledged packet timed out
rx timeout
waiting for acknowledged packet timed out
waiting for acknowledged packet timed out
rx timeout
waiting for acknowledged packet timed out
waiting for acknowledged packet timed out
[ERROR] [1525483508.990614907]: failed
[ERROR] [1525483508.990802433]: unable to connect
rx timeout
rx timeout
[fcu-1] process has died [pid 18290, exit code 255, cmd /home/giovanni/experimentos/asctec_ros/asctec5_ws/devel/lib/asctec_hl_interface/hl_node __name:=fcu __log:=/home/giovanni/.ros/log/d3525b36-4ffa-11e8-8c40-00265e82a72d/fcu-1.log].
log file: /home/giovanni/.ros/log/d3525b36-4ffa-11e8-8c40-00265e82a72d/fcu-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

http://wiki.asctec.de/display/AR/XBee+Modules

Thanks
